### ISSUE TITLE
Unpinned boto3 dependency upgrades botocore globally and breaks aiobotocore consumers in Home Assistant

### ISSUE THREAD

**Issue by owine** [Gentex-Corporation/homelink-integration-api#6]
## Summary

`homelink-integration-api==0.0.1` declares `boto3` with no version constraint in `pyproject.toml`:

```toml
dependencies = ["python-decouple>=3.8", "boto3"]
```

When Home Assistant installs this package at runtime, which happens as soon as a user opens the HomeLink config flow in the UI (even if they cancel without finishing), pip resolves `boto3` to the newest release on PyPI and pulls `botocore` forward with it. That breaks Home Assistant integrations that use `aiobotocore`, because `aiobotocore` pins `botocore` to a narrow range.

## Impact

On a clean Home Assistant OS install, this is enough to break unrelated integrations:

1. Settings → Devices & Services → Add Integration → "HomeLink". Start the flow (no real device required) and cancel out.
2. Restart Home Assistant.
3. Cloudflare R2, IDrive e2, and Nice G.O. fail to set up with:

   ```
   TypeError: ClientArgsCreator.compute_endpoint_resolver_builtin_defaults()
   missing 1 required positional argument: 's3_disable_express_session_auth'
   ```

The runtime ends up with something like:

```
aiobotocore 2.21.1   (requires botocore >=1.37.0,<1.37.2)
boto3       1.43.4
botocore    1.43.4
```

`pipdeptree` confirms the conflict:

```
aiobotocore==2.21.1
 - botocore [required: >=1.37.0,<1.37.2, installed: 1.43.4]
```

Reproduced on HA OS 2026.5.0, ARM64. Full upstream context: https://github.com/home-assistant/core/issues/168539#issuecomment-4407389380

## Suggested fix

Add an upper bound on `boto3` so pip can't drag it past what `aiobotocore` allows:

```toml
dependencies = ["python-decouple>=3.8", "boto3>=1.34,<1.38"]
```

`>=1.34,<1.38` works with `aiobotocore 2.21.x`, which is what HA ships today. Raise the cap when HA moves to 3.x.

**Comment by owine** [comment]
Opened #7 with the suggested cap.

**Comment by rjones-gentex** [comment]
Thanks for bringing this to our attention, I will merge #7 and create a PR update for the core repo.
